framework:
    enabled_locales: [ 'ca', 'es', 'en' ]
    default_locale: es
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
