vich_uploader:
    db_driver: orm

    mappings:
        vehicles_images:
            uri_prefix: /images/vehicles
            upload_destination: '%kernel.project_dir%/public/images/vehicles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
